export VISUAL="vim"
export LANG=zh_CN.UTF-8
export MYVIMRC=~/.vimrc
export TERM="xterm-256color"
export FZF_COMPLETION_TRIGGER=''
export HOMEBREW_NO_AUTO_UPDATE=true
export PATH="$HOME/.npm-global/bin:$PATH"

#Java
# alias java18="export JAVA_HOME=`/usr/libexec/java_home -v 18.0.2`; java -version"
# alias java17="export JAVA_HOME=`/usr/libexec/java_home -v 17.0.4`; java -version"
# alias java8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_341`; java -version"
# export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_341`
# export JRE_HOME=$JAVA_HOME/jre
# export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
# export M3_HOME=/opt/maven
# export PATH=$PATH:$JAVA_HOME/bin:$M3_HOME/bin

#Golang
export GO111MODULE=on
export GOPATH=$HOME/go
export GOPBIN=$HOME/go/bin
