export PATH=$HOME/bin:/usr/local/bin:$PATH
# Oh-My-Zsh {{{1
export ZSH="$HOME/.oh-my-zsh"
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

plugins=(
    aws
    colored-man-pages
    docker
    git
    golang
    helm
    httpie
    kubectl
    npm
    terraform
    tmux
    vi-mode
    you-should-use
    z
    zsh-autosuggestions
    zsh-nvm
)
# Settings that must be applid before loading Oh-My-Zsh {{{2
# Set the theme
ZSH_THEME="powerlevel10k/powerlevel10k"
# 使用 区分大小写 完成
CASE_SENSITIVE="true"
# 修复慢粘贴
DISABLE_MAGIC_FUNCTIONS=true
# Set the default umask
umask 022
#}}}

# 加载 oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Source files {{{2
# Load aliases
source ~/.dotfile/zsh/aliases.zsh
# Completion {{{3
# 设置描述格式以启用组支持
zstyle ':completion:*:descriptions' format '[%d]'
# 完成 `git checkout` 时禁用排序
zstyle ':completion:*:git-checkout:*' sort false
# 仅显示目标标记以完成 make 命令
zstyle ':completion:*:*:make::' tag-order 'targets variables'
# 在完成“ kill”时预览命令行参数
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"
#}}}

# Other {{{4
# disable highlighting of pasted text
zle_highlight=('paste:none')

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#}}}

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

